### ISSUE TITLE
Use NodaTime instead!

### ISSUE THREAD

**Issue by cottsak** [dennisroche/DateTimeProvider#29]
[Learn how to use NodaTime's `Instant`](http://nodatime.org/2.2.x/userguide/concepts) and the `IClock` interface which pretty much does what this is trying to do.

**Comment by dennisroche** [comment]
👍 I agree  and would recommend using NodaTime. To achieve a similar approach using Noda, see https://gist.github.com/dennisroche/4b60ec1a8aa6e2debfa0fa2da904a95f
